qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch1 -l mem_free=1G,h_vmem=8G -q short.q batch1.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch2 -l mem_free=1G,h_vmem=8G -q short.q batch2.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch3 -l mem_free=1G,h_vmem=8G -q short.q batch3.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch4 -l mem_free=1G,h_vmem=8G -q short.q batch4.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch5 -l mem_free=1G,h_vmem=8G -q short.q batch5.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch6 -l mem_free=1G,h_vmem=8G -q short.q batch6.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch7 -l mem_free=1G,h_vmem=8G -q short.q batch7.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch8 -l mem_free=1G,h_vmem=8G -q short.q batch8.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch9 -l mem_free=1G,h_vmem=8G -q short.q batch9.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch10 -l mem_free=1G,h_vmem=8G -q short.q batch10.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch11 -l mem_free=1G,h_vmem=8G -q short.q batch11.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch12 -l mem_free=1G,h_vmem=8G -q short.q batch12.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch13 -l mem_free=1G,h_vmem=8G -q short.q batch13.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch14 -l mem_free=1G,h_vmem=8G -q short.q batch14.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch15 -l mem_free=1G,h_vmem=8G -q short.q batch15.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch16 -l mem_free=1G,h_vmem=8G -q short.q batch16.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch17 -l mem_free=1G,h_vmem=8G -q short.q batch17.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch18 -l mem_free=1G,h_vmem=8G -q short.q batch18.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch19 -l mem_free=1G,h_vmem=8G -q short.q batch19.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch20 -l mem_free=1G,h_vmem=8G -q short.q batch20.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch21 -l mem_free=1G,h_vmem=8G -q short.q batch21.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch22 -l mem_free=1G,h_vmem=8G -q short.q batch22.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch23 -l mem_free=1G,h_vmem=8G -q short.q batch23.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch24 -l mem_free=1G,h_vmem=8G -q short.q batch24.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch25 -l mem_free=1G,h_vmem=8G -q short.q batch25.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch26 -l mem_free=1G,h_vmem=8G -q short.q batch26.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch27 -l mem_free=1G,h_vmem=8G -q short.q batch27.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch28 -l mem_free=1G,h_vmem=8G -q short.q batch28.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch29 -l mem_free=1G,h_vmem=8G -q short.q batch29.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch30 -l mem_free=1G,h_vmem=8G -q short.q batch30.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch31 -l mem_free=1G,h_vmem=8G -q short.q batch31.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch32 -l mem_free=1G,h_vmem=8G -q short.q batch32.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch33 -l mem_free=1G,h_vmem=8G -q short.q batch33.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch34 -l mem_free=1G,h_vmem=8G -q short.q batch34.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch35 -l mem_free=1G,h_vmem=8G -q short.q batch35.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch36 -l mem_free=1G,h_vmem=8G -q short.q batch36.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch37 -l mem_free=1G,h_vmem=8G -q short.q batch37.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch38 -l mem_free=1G,h_vmem=8G -q short.q batch38.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch39 -l mem_free=1G,h_vmem=8G -q short.q batch39.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch40 -l mem_free=1G,h_vmem=8G -q short.q batch40.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch41 -l mem_free=1G,h_vmem=8G -q short.q batch41.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch42 -l mem_free=1G,h_vmem=8G -q short.q batch42.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch43 -l mem_free=1G,h_vmem=8G -q short.q batch43.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch44 -l mem_free=1G,h_vmem=8G -q short.q batch44.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch45 -l mem_free=1G,h_vmem=8G -q short.q batch45.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch46 -l mem_free=1G,h_vmem=8G -q short.q batch46.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch47 -l mem_free=1G,h_vmem=8G -q short.q batch47.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch48 -l mem_free=1G,h_vmem=8G -q short.q batch48.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch49 -l mem_free=1G,h_vmem=8G -q short.q batch49.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch50 -l mem_free=1G,h_vmem=8G -q short.q batch50.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch51 -l mem_free=1G,h_vmem=8G -q short.q batch51.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch52 -l mem_free=1G,h_vmem=8G -q short.q batch52.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch53 -l mem_free=1G,h_vmem=8G -q short.q batch53.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch54 -l mem_free=1G,h_vmem=8G -q short.q batch54.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch55 -l mem_free=1G,h_vmem=8G -q short.q batch55.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch56 -l mem_free=1G,h_vmem=8G -q short.q batch56.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch57 -l mem_free=1G,h_vmem=8G -q short.q batch57.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch58 -l mem_free=1G,h_vmem=8G -q short.q batch58.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch59 -l mem_free=1G,h_vmem=8G -q short.q batch59.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch60 -l mem_free=1G,h_vmem=8G -q short.q batch60.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch61 -l mem_free=1G,h_vmem=8G -q short.q batch61.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch62 -l mem_free=1G,h_vmem=8G -q short.q batch62.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch63 -l mem_free=1G,h_vmem=8G -q short.q batch63.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch64 -l mem_free=1G,h_vmem=8G -q short.q batch64.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch65 -l mem_free=1G,h_vmem=8G -q short.q batch65.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch66 -l mem_free=1G,h_vmem=8G -q short.q batch66.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch67 -l mem_free=1G,h_vmem=8G -q short.q batch67.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch68 -l mem_free=1G,h_vmem=8G -q short.q batch68.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch69 -l mem_free=1G,h_vmem=8G -q short.q batch69.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch70 -l mem_free=1G,h_vmem=8G -q short.q batch70.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch71 -l mem_free=1G,h_vmem=8G -q short.q batch71.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch72 -l mem_free=1G,h_vmem=8G -q short.q batch72.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch73 -l mem_free=1G,h_vmem=8G -q short.q batch73.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch74 -l mem_free=1G,h_vmem=8G -q short.q batch74.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch75 -l mem_free=1G,h_vmem=8G -q short.q batch75.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch76 -l mem_free=1G,h_vmem=8G -q short.q batch76.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch77 -l mem_free=1G,h_vmem=8G -q short.q batch77.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch78 -l mem_free=1G,h_vmem=8G -q short.q batch78.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch79 -l mem_free=1G,h_vmem=8G -q short.q batch79.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch80 -l mem_free=1G,h_vmem=8G -q short.q batch80.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch81 -l mem_free=1G,h_vmem=8G -q short.q batch81.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch82 -l mem_free=1G,h_vmem=8G -q short.q batch82.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch83 -l mem_free=1G,h_vmem=8G -q short.q batch83.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch84 -l mem_free=1G,h_vmem=8G -q short.q batch84.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch85 -l mem_free=1G,h_vmem=8G -q short.q batch85.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch86 -l mem_free=1G,h_vmem=8G -q short.q batch86.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch87 -l mem_free=1G,h_vmem=8G -q short.q batch87.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch88 -l mem_free=1G,h_vmem=8G -q short.q batch88.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch89 -l mem_free=1G,h_vmem=8G -q short.q batch89.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch90 -l mem_free=1G,h_vmem=8G -q short.q batch90.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch91 -l mem_free=1G,h_vmem=8G -q short.q batch91.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch92 -l mem_free=1G,h_vmem=8G -q short.q batch92.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch93 -l mem_free=1G,h_vmem=8G -q short.q batch93.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch94 -l mem_free=1G,h_vmem=8G -q short.q batch94.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch95 -l mem_free=1G,h_vmem=8G -q short.q batch95.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch96 -l mem_free=1G,h_vmem=8G -q short.q batch96.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch97 -l mem_free=1G,h_vmem=8G -q short.q batch97.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch98 -l mem_free=1G,h_vmem=8G -q short.q batch98.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch99 -l mem_free=1G,h_vmem=8G -q short.q batch99.sh
qsub -V -cwd -M lshmk17@lshtm.ac.uk -m ea -N batch100 -l mem_free=1G,h_vmem=8G -q short.q batch100.sh
